"""initial schema

Revision ID: 1a5fbecbf9b4
Revises: 
Create Date: 2025-09-11 11:19:23.767950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5fbecbf9b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('return_path', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('html_raw', sa.Text(), nullable=True),
    sa.Column('has_text', sa.Integer(), nullable=False),
    sa.Column('has_html', sa.Integer(), nullable=False),
    sa.Column('urls', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('attachments_count', sa.Integer(), nullable=False),
    sa.Column('list_unsubscribe', sa.Text(), nullable=True),
    sa.Column('spf_result', sa.String(length=16), nullable=True),
    sa.Column('dkim_result', sa.String(length=16), nullable=True),
    sa.Column('dmarc_result', sa.String(length=16), nullable=True),
    sa.Column('received_ips', sa.JSON(), nullable=True),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('raw_eml_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emails'))
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index('ix_emails_message_id', ['message_id'], unique=False)
        batch_op.create_index('ix_emails_sender', ['sender'], unique=False)
        batch_op.create_index('ix_emails_timestamp', ['timestamp'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('body_preview', sa.String(length=500), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('header_flags', sa.JSON(), nullable=True),
    sa.Column('probs', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name=op.f('ck_scans_confidence')),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_scans_email_id_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index('ix_scans_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_scans_email_id', ['email_id'], unique=False)
        batch_op.create_index('ix_scans_label', ['label'], unique=False)
        batch_op.create_index('ix_scans_sender', ['sender'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index('ix_scans_sender')
        batch_op.drop_index('ix_scans_label')
        batch_op.drop_index('ix_scans_email_id')
        batch_op.drop_index('ix_scans_created_at')

    op.drop_table('scans')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index('ix_emails_timestamp')
        batch_op.drop_index('ix_emails_sender')
        batch_op.drop_index('ix_emails_message_id')

    op.drop_table('emails')
    # ### end Alembic commands ###
