"""create emails table and link scans

Revision ID: 22e84fec2081
Revises: a7276b896265
Create Date: 2025-08-24 11:01:29.158600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e84fec2081'
down_revision: Union[str, Sequence[str], None] = 'a7276b896265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('return_path', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('html_raw', sa.Text(), nullable=True),
    sa.Column('has_text', sa.Integer(), nullable=False),
    sa.Column('has_html', sa.Integer(), nullable=False),
    sa.Column('urls', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('attachments_count', sa.Integer(), nullable=False),
    sa.Column('list_unsubscribe', sa.Text(), nullable=True),
    sa.Column('spf_result', sa.String(length=16), nullable=True),
    sa.Column('dkim_result', sa.String(length=16), nullable=True),
    sa.Column('dmarc_result', sa.String(length=16), nullable=True),
    sa.Column('received_ips', sa.JSON(), nullable=True),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('raw_eml_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emails'))
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index('ix_emails_message_id', ['message_id'], unique=False)
        batch_op.create_index('ix_emails_sender', ['sender'], unique=False)
        batch_op.create_index('ix_emails_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('header_flags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('model_version', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('direction', sa.String(length=16), nullable=True))
        batch_op.drop_index(batch_op.f('ix_scans_id'))
        batch_op.create_index('ix_scans_email_id', ['email_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_scans_email_id_emails'), 'emails', ['email_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_scans_email_id_emails'), type_='foreignkey')
        batch_op.drop_index('ix_scans_email_id')
        batch_op.create_index(batch_op.f('ix_scans_id'), ['id'], unique=False)
        batch_op.drop_column('direction')
        batch_op.drop_column('model_version')
        batch_op.drop_column('header_flags')
        batch_op.drop_column('email_id')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index('ix_emails_timestamp')
        batch_op.drop_index('ix_emails_sender')
        batch_op.drop_index('ix_emails_message_id')

    op.drop_table('emails')
    # ### end Alembic commands ###
